### Create User 1
POST http://localhost:3000/users
Content-Type: application/json

{
  "userName": "Hatem Saleh",
  "password": "password123",
  "email": "hatem@gmail.com",
  "userRole": "ADMIN"
}

### Create User 2
POST http://localhost:3000/users
Content-Type: application/json

{
  "userName": "jack Smith",
  "email": "steeve@example.com",
  "password": "password1234",
  "userRole": "techer"
}

### Create Professor 1
POST http://localhost:3000/users
Content-Type: application/json

{
  "userName": "adam",
  "email": "adam@example.com",
  "password": "123123123",
  "userRole": "student"
}

### Create Professor 2
POST http://localhost:3000/users
Content-Type: application/json

{
  "userName": "Dr. James Lee",
  "email": "james.lee@example.com",
  "password": "lecture123",
  "phone": "123-456-7890",
  "userRole": "PROFESSOR"
}


GET http://localhost:3000/users
Content-Type: application/json

{
  "email": "james.lee@example.com",
}
